### ISSUE TITLE
Cannot read properties of undefined

### ISSUE THREAD

**Issue by LLinVIP** [zguolee/vite-plugin-unocss-to-uni#1]
Everytime I use this plugin in vite.config.ts ,this will cause a problem：
![image](https://user-images.githubusercontent.com/68938689/161456902-55c9e7a1-a5dc-4726-8f7c-369f8b8d903d.png)
![image](https://user-images.githubusercontent.com/68938689/161456930-12820837-e622-4280-af73-e1a737ca59b2.png)
I've unistalled and reinstalled this plugin ,but in vain. Please tell me how to solve this problem. Thanks.

**Comment by nei1ee** [comment]
Thanks for asking, but I can't reproduce this problem, can you give me the source code of this situation?

**Comment by LLinVIP** [comment]
I‘ve used colorUI in current program, may be there is a confilict with it🤣. After adjusting some code, there is a new problem:
![image](https://user-images.githubusercontent.com/68938689/161462142-585dbf43-0a49-4718-8b89-f9df27a57b50.png)
🫣

**Comment by LLinVIP** [comment]
Perhaps I should learn unocss carefully🤣

**Comment by nei1ee** [comment]
Because the plugin replaces `class` with regular expressions, the `class` and `:class` attributes need to be on a single line, for example: 
```html
  <div
    class="py-1.5 dark:bg-opacity-30"
    :class="true ? 'bg-gray-200' : ''"
  >
```
Now I don't have a better solution.

**Comment by LLinVIP** [comment]
> Because the plugin replaces `class` with regular expressions, the `class` and `:class` attributes need to be on a single line, for example:
> 
> ```
>   <div
>     class="py-1.5 dark:bg-opacity-30"
>     :class="true ? 'bg-gray-200' : ''"
>   >
> ```
> 
> Now I don't have a better solution.

Thanks, briliant developer. Sorry for inconviencing you, there is a new question that if I use colorui and unocss at same time, some styles of colorui will be covered by the unocss. Is there any method to prevent this situation?

**Comment by nei1ee** [comment]
`unocss.config.ts` provides a `preprocess` method, which may filter some ColorUI styles.
```js
preprocess: (t) => {
  const classMargin = /^m-\d+\.?\d*$/
  if (!classMargin.test(t)) return t
},
```
The above code just doesn't handle things like `m-1.5`.
